server:
  port: 8081

spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/ewallet_auth
      database: ewallet_auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ewallet-super-secret-key-2024-must-be-at-least-256-bits-long!!
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ewallet: DEBUG